meta: config/boards/hellen_mm100_meta.h

pins:
  - pin: EGT1+
    type: egt
    function: "EGT1 + (Chromel) (Mini-Buchse PCC-SMP-K)"
    ts_name: "EGT1+"

  - pin: EGT1-
    type: egt
    function: "EGT1 - (Alumel)"
    ts_name: "EGT1-"

  - pin: EGT2+
    type: egt
    function: "EGT2 + (Chromel) (Mini-Buchse PCC-SMP-K)"
    ts_name: "EGT2+"

  - pin: EGT2-
    type: egt
    function: "EGT2 - (Alumel)"
    ts_name: "EGT2-"

  - pin: EGT3+
    type: egt
    function: "EGT3 + (Chromel) (Mini-Buchse PCC-SMP-K)"
    ts_name: "EGT3+"

  - pin: EGT3-
    type: egt
    function: "EGT3 - (Alumel)"
    ts_name: "EGT3-"

  - pin: EGT4+
    type: egt
    function: "EGT4 + (Chromel) (Mini-Buchse PCC-SMP-K)"
    ts_name: "EGT4+"

  - pin: EGT4-
    type: egt
    function: "EGT4 - (Alumel)"
    ts_name: "EGT4-"

info:
  cid: egt
  title: "Side EGT sockets (miniature type K)"
  name: uaefi-moto
  directory: hellen/uaefi-moto
